/**
 * EBML Duration Patcher for WebM files generated by MediaRecorder.
 * 
 * MediaRecorder streams video live, so Chrome and mobile browsers cannot know
 * the final duration upfront and write Segment Info without a Duration tag
 * (or with duration = 0). As a result, Android Gallery and MediaMetadataRetriever
 * index the recorded file as 0:00.
 * 
 * Traditional fix-webm-duration libraries re-serialized every cluster in JavaScript,
 * which corrupted cluster timestamps and caused the video to play at lightspeed.
 * 
 * This patcher operates SURGICALLY:
 * 1. It locates the EBML Header and Segment Info container (0x1549A966).
 * 2. It reads the exact TimecodeScale (default 1,000,000 ns = 1 ms).
 * 3. It calculates duration in TimecodeScale units (durationSec * 1e9 / timecodeScaleNs).
 * 4. It updates or inserts the Duration element (0x4489) using IEEE 754 Float64.
 * 5. It leaves EVERY video frame, cluster, and audio packet 100% untouched bit-for-bit.
 */

function readVint(
  u8: Uint8Array,
  offset: number
): { val: number; len: number; isUnknown: boolean } | null {
  if (offset >= u8.length) return null;
  const first = u8[offset];
  let len = 1;
  let mask = 0x80;
  while (len <= 8 && (first & mask) === 0) {
    len++;
    mask >>= 1;
  }
  if (len > 8) return null;
  let val = first & (mask - 1);
  for (let i = 1; i < len; i++) {
    val = (val * 256) + u8[offset + i];
  }
  const isUnknown =
    first === 0x01 && len === 8 && u8.slice(offset + 1, offset + 8).every((b) => b === 0xff);
  return { val, len, isUnknown };
}

function encodeVint(val: number, minLen = 1): Uint8Array {
  let len = minLen;
  if (val >= 0x7f && len === 1) len = 2;
  if (val >= 0x3fff && len === 2) len = 3;
  if (val >= 0x1fffff && len === 3) len = 4;

  const buf = new Uint8Array(len);
  let temp = val;
  for (let i = len - 1; i > 0; i--) {
    buf[i] = temp & 0xff;
    temp = Math.floor(temp / 256);
  }
  buf[0] = (1 << (8 - len)) | (temp & ((1 << (8 - len)) - 1));
  return buf;
}

/**
 * Scans clusters in WebM to find the largest timestamp if targetDurationSec is not provided.
 */
function scanClusterDuration(
  u8: Uint8Array,
  startOffset: number,
  timecodeScaleNs: number
): number {
  let pos = startOffset;
  let maxTimecode = 0;
  const limit = Math.min(u8.length - 8, startOffset + 50_000_000); // scan up to 50MB
  while (pos + 8 < limit) {
    // Cluster ID: 0x1F43B675
    if (u8[pos] === 0x1f && u8[pos + 1] === 0x43 && u8[pos + 2] === 0xb6 && u8[pos + 3] === 0x75) {
      const cLen = readVint(u8, pos + 4);
      if (!cLen) break;
      const inner = pos + 4 + cLen.len;
      const innerEnd = cLen.isUnknown
        ? Math.min(u8.length, inner + 250)
        : Math.min(u8.length, inner + cLen.val);
      // Scan for Timecode (0xE7)
      for (let i = inner; i < innerEnd - 2; i++) {
        if (u8[i] === 0xe7) {
          const tLen = readVint(u8, i + 1);
          if (tLen && tLen.val <= 8) {
            let tc = 0;
            for (let j = 0; j < tLen.val; j++) {
              tc = (tc * 256) + u8[i + 1 + tLen.len + j];
            }
            if (tc > maxTimecode) maxTimecode = tc;
          }
          break;
        }
      }
      if (cLen.isUnknown) {
        pos += 4;
      } else {
        pos = pos + 4 + cLen.len + cLen.val;
      }
    } else {
      pos++;
    }
  }
  return (maxTimecode * timecodeScaleNs) / 1e9;
}

/**
 * Surgically injects or updates the Duration element in Segment Info
 * without touching any audio or video clusters.
 */
export async function safeFixWebm(
  rawBlob: Blob,
  targetDurationSec?: number
): Promise<Blob> {
  if (rawBlob.size < 40) return rawBlob;

  try {
    const arrayBuffer = await rawBlob.arrayBuffer();
    const u8 = new Uint8Array(arrayBuffer);
    const view = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);

    // 1. Verify EBML Header (0x1A45DFA3)
    if (view.getUint32(0) !== 0x1a45dfa3) {
      return rawBlob;
    }
    const ebmlLen = readVint(u8, 4);
    if (!ebmlLen) return rawBlob;

    const segOffset = 4 + ebmlLen.len + ebmlLen.val;
    if (segOffset + 4 >= u8.length || view.getUint32(segOffset) !== 0x18538067) {
      return rawBlob;
    }

    const segLenPos = segOffset + 4;
    const segLen = readVint(u8, segLenPos);
    if (!segLen) return rawBlob;

    const segHeaderEnd = segLenPos + segLen.len;
    let pos = segHeaderEnd;
    let infoPos = -1;
    let infoLen: { val: number; len: number; isUnknown: boolean } | null = null;

    // Search for Segment Info (0x1549A966)
    const searchLimit = Math.min(u8.length - 8, segHeaderEnd + 8192);
    while (pos < searchLimit) {
      if (view.getUint32(pos) === 0x1549a966) {
        infoPos = pos;
        infoLen = readVint(u8, pos + 4);
        break;
      }
      pos++;
    }

    if (infoPos === -1 || !infoLen) {
      return rawBlob;
    }

    const infoLenPos = infoPos + 4;
    const infoDataStart = infoLenPos + infoLen.len;
    const infoDataEnd = infoDataStart + infoLen.val;

    // 2. Read TimecodeScale (0x2AD7B1) inside Info
    let timecodeScaleNs = 1_000_000; // default 1ms
    let durOffset = -1;
    let durLen = 0;
    let p = infoDataStart;

    while (p < infoDataEnd) {
      // TimecodeScale: 0x2AD7B1 (3 bytes)
      if (p + 3 <= infoDataEnd && u8[p] === 0x2a && u8[p + 1] === 0xd7 && u8[p + 2] === 0xb1) {
        const tcLen = readVint(u8, p + 3);
        if (tcLen) {
          let tcVal = 0;
          for (let i = 0; i < tcLen.val; i++) {
            tcVal = (tcVal * 256) + u8[p + 3 + tcLen.len + i];
          }
          timecodeScaleNs = tcVal || 1_000_000;
          p = p + 3 + tcLen.len + tcLen.val;
          continue;
        }
      }
      // Duration: 0x4489 (2 bytes)
      if (p + 2 <= infoDataEnd && u8[p] === 0x44 && u8[p + 1] === 0x89) {
        const dLen = readVint(u8, p + 2);
        if (dLen) {
          durOffset = p;
          durLen = 2 + dLen.len + dLen.val;
          break;
        }
      }
      p++;
    }

    // Determine final duration in seconds
    let finalDurSec = targetDurationSec && targetDurationSec > 0 ? targetDurationSec : 0;
    if (!finalDurSec) {
      finalDurSec = scanClusterDuration(u8, infoDataEnd, timecodeScaleNs);
    }
    if (!finalDurSec || finalDurSec <= 0) {
      return rawBlob;
    }

    // Duration value in units of TimecodeScale
    const durationInScaleUnits = (finalDurSec * 1e9) / timecodeScaleNs;

    // Case A: Duration already present in Info -> overwrite in place!
    if (durOffset !== -1) {
      const dVint = readVint(u8, durOffset + 2);
      if (dVint) {
        const dValOffset = durOffset + 2 + dVint.len;
        const dValLen = durLen - (dValOffset - durOffset);
        if (dValLen === 4) {
          view.setFloat32(dValOffset, durationInScaleUnits, false);
          return new Blob([u8], { type: rawBlob.type || 'video/webm' });
        } else if (dValLen === 8) {
          view.setFloat64(dValOffset, durationInScaleUnits, false);
          return new Blob([u8], { type: rawBlob.type || 'video/webm' });
        }
      }
    }

    // Case B: Duration not present -> insert 11-byte Duration element into Info
    // 0x44, 0x89 (2 bytes ID) + 0x88 (1 byte VINT len 8) + 8 bytes Float64
    const durElem = new Uint8Array(11);
    durElem[0] = 0x44;
    durElem[1] = 0x89;
    durElem[2] = 0x88;
    const durView = new DataView(durElem.buffer);
    durView.setFloat64(3, durationInScaleUnits, false);

    const newInfoVal = infoLen.val + 11;
    const newInfoVint = encodeVint(newInfoVal, infoLen.len);
    const vintDiff = newInfoVint.length - infoLen.len;

    const out = new Uint8Array(u8.length + 11 + vintDiff);
    // 1. Copy everything before Info length
    out.set(u8.subarray(0, infoLenPos), 0);
    // 2. Set new Info VINT length
    out.set(newInfoVint, infoLenPos);
    // 3. Copy existing Info data
    const newInfoDataStart = infoLenPos + newInfoVint.length;
    out.set(u8.subarray(infoDataStart, infoDataEnd), newInfoDataStart);
    // 4. Insert new Duration element at end of Info
    out.set(durElem, newInfoDataStart + infoLen.val);
    // 5. Copy ALL remaining data (Tracks, Clusters, frames) completely untouched!
    out.set(u8.subarray(infoDataEnd), newInfoDataStart + infoLen.val + 11);

    // 6. Update Segment length if it was finite
    if (!segLen.isUnknown) {
      const newSegVal = segLen.val + 11 + vintDiff;
      const newSegVint = encodeVint(newSegVal, segLen.len);
      if (newSegVint.length === segLen.len) {
        out.set(newSegVint, segLenPos);
      }
    }

    return new Blob([out], { type: rawBlob.type || 'video/webm' });
  } catch (err) {
    console.warn('safeFixWebm duration patch error, returning original blob:', err);
    return rawBlob;
  }
}
